/**
 * Author Alain Ibrahim 20/11/2015
 */
var stratigraphie_international = [
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Quaternaire','epoque':'Holocène','etage':'' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Quaternaire','epoque':'Pléistocène','etage':'supérieur' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Quaternaire','epoque':'Pléistocène','etage':'Moyen' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Quaternaire','epoque':'Pléistocène','etage':'Calabrien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Quaternaire','epoque':'Pléistocène','etage':'Gélasien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Pliocène','etage':'Piacenzien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Pliocène','etage':'Zancléen' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Messinien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Tortonien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Serravallien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Langhien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Burdigalien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Néogène','epoque':'Miocène','etage':'Aquitanien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Oligocène','etage':'Chattien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Oligocène','etage':'Rupélien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Eocène','etage':'Priabonien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Eocène','etage':'Bartonien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Eocène','etage':'Lutétien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Eocène','etage':'Yprésien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Paléocène','etage':'Thanétien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Paléocène','etage':'Sélandien' } ,
    {'eon':'Phanérozoïque','ere':'Cénozoïque','periode':'Paléogène','epoque':'Paléocène','etage':'Danien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Maastrichtien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Campanien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Santonien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Coniacien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Turonien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Supérieur','etage':'Cénomanien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Albien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Aptien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Barrémien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Hauterivien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Valanginien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Crétacé','epoque':'Inférieur','etage':'Berriasien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Supérieur','etage':'Tithonien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Supérieur','etage':'Kimméridgien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Supérieur','etage':'Oxfordien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Moyen','etage':'Callovien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Moyen','etage':'Bathonien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Moyen','etage':'Bajocien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Moyen','etage':'Aalénien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Inférieur','etage':'Toarcien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Inférieur','etage':'Pliensbachien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Inférieur','etage':'Sinémurien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Jurassique','epoque':'Inférieur','etage':'Hettangien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Supérieur','etage':'Rhétien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Supérieur','etage':'Norien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Supérieur','etage':'Carnien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Moyen','etage':'Ladinien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Moyen','etage':'Anisien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Inférieur','etage':'Olenékien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Trias','epoque':'Inférieur','etage':'Induen' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Lopingien','etage':'Changhsingien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Lopingien','etage':'Wuchiapingien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Guadalupien','etage':'Capitanien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Guadalupien','etage':'Wordien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Guadalupien','etage':'Roadien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Cisuralien','etage':'Kungurien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Cisuralien','etage':'Artinskien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Cisuralien','etage':'Sakmarien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Permien','epoque':'Cisuralien','etage':'Assélien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Pennsylvanien sup','etage':'Gzhélien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Pennsylvanien sup','etage':'Kasimovien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Pennsylvanien moy','etage':'Moscovien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Pennsylvanien inf','etage':'Bashkirien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Mississipien sup','etage':'Serpukhovien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Mississipien moy','etage':'Viséen' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Carbonifère','epoque':'Mississipien inf','etage':'Tournaisien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Supérieur','etage':'Famennien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Supérieur','etage':'Frasnien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Moyen','etage':'Givétien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Moyen','etage':'Eifélien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Inférieur','etage':'Emsien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Inférieur','etage':'Praguien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Dévonien','epoque':'Inférieur','etage':'Lochkovien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Pridoli','etage':'' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Ludlow','etage':'Ludfordien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Ludlow','etage':'Gorstien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Wenlock','etage':'Homérien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Wenlock','etage':'Sheinwoodien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Llandovery','etage':'Télychien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Llandovery','etage':'Aéronien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Silurien','epoque':'Llandovery','etage':'Rhuddanien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Supérieur','etage':'Hirnantien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Supérieur','etage':'Katien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Supérieur','etage':'Sandbien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Moyen','etage':'Darriwilien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Moyen','etage':'Dapingien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Inférieur','etage':'Floien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Ordovicien','epoque':'Inférieur','etage':'trémadocien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Furongien','etage':'Etage 10' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Furongien','etage':'Jiangshanien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Furongien','etage':'Paibien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Séries 3','etage':'Guzhangien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Séries 4','etage':'Drumien' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Séries 5','etage':'Etage 5' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Séries 2','etage':'Etage 4' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Séries 3','etage':'Etage 3' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Terreneuvien','etage':'Etage 2' } ,
    {'eon':'Phanérozoïque','ere':'Mésozoïque','periode':'Cambrien','epoque':'Terreneuvien','etage':'Fortunien' } ,
    {'eon':'Protérozoïque','ere':'Néoprotérozoïque','periode':'Ediacarien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Néoprotérozoïque','periode':'Cryogénien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Néoprotérozoïque','periode':'Tonien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Mésoprotérozoïque','periode':'Sténien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Mésoprotérozoïque','periode':'Ectasien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Mésoprotérozoïque','periode':'Calymmien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Paléoprotérozoïque','periode':'Stathérien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Paléoprotérozoïque','periode':'Orosirien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Paléoprotérozoïque','periode':'Rhyacien','epoque':'','etage':'' } ,
    {'eon':'Protérozoïque','ere':'Paléoprotérozoïque','periode':'Sidérien','epoque':'','etage':'' } ,
    {'eon':'Archéen','ere':'Néoarchéen','periode':'','epoque':'','etage':'' } ,
    {'eon':'Archéen','ere':'Mésoarchéen','periode':'','epoque':'','etage':'' } ,
    {'eon':'Archéen','ere':'Paléoarchéen','periode':'','epoque':'','etage':'' } ,
    {'eon':'Archéen','ere':'Eoarchéen','periode':'','epoque':'','etage':'' } ,
    {'eon':'Hadéen','ere':'','periode':'','epoque':'','etage':'' }
];
